# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tooyue' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Tooyue
  # U-Share SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’

  # 集成微信(精简版0.2M)
    pod ‘UMengUShare/Social/ReducedWeChat'

  # 集成QQ/QZone/TIM(完整版7.6M)
    pod ‘UMengUShare/Social/QQ'

end
